var annotated_dup =
[
    [ "BadInitializationException", "class_bad_initialization_exception.html", "class_bad_initialization_exception" ],
    [ "Biome", "class_biome.html", "class_biome" ],
    [ "BiomePlacer", "class_biome_placer.html", "class_biome_placer" ],
    [ "BiomeProvider", "class_biome_provider.html", "class_biome_provider" ],
    [ "Block", "class_block.html", "class_block" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "Chunk", "class_chunk.html", "class_chunk" ],
    [ "ChunkBlocks", "class_chunk_blocks.html", "class_chunk_blocks" ],
    [ "ChunkFrame", "class_chunk_frame.html", "class_chunk_frame" ],
    [ "ChunkManager", "class_chunk_manager.html", "class_chunk_manager" ],
    [ "ChunkUtils", "class_chunk_utils.html", null ],
    [ "ElementBuffer", "class_element_buffer.html", "class_element_buffer" ],
    [ "EngineException", "class_engine_exception.html", "class_engine_exception" ],
    [ "FileUtils", "class_file_utils.html", null ],
    [ "FPSCounter", "class_f_p_s_counter.html", "class_f_p_s_counter" ],
    [ "HumanInterfaceDevice", "class_human_interface_device.html", "class_human_interface_device" ],
    [ "LibraryBugException", "class_library_bug_exception.html", "class_library_bug_exception" ],
    [ "Log", "class_log.html", "class_log" ],
    [ "MainMenu", "class_main_menu.html", "class_main_menu" ],
    [ "Metadata", "class_metadata.html", "class_metadata" ],
    [ "MismatchException", "class_mismatch_exception.html", "class_mismatch_exception" ],
    [ "Noise", "class_noise.html", "class_noise" ],
    [ "Noise2D", "class_noise2_d.html", "class_noise2_d" ],
    [ "Noise3D", "class_noise3_d.html", "class_noise3_d" ],
    [ "NotFoundException", "class_not_found_exception.html", "class_not_found_exception" ],
    [ "Sandbox", "class_sandbox.html", "class_sandbox" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "UninitializedPropertyAccessException", "class_uninitialized_property_access_exception.html", "class_uninitialized_property_access_exception" ],
    [ "VertexArray", "class_vertex_array.html", "class_vertex_array" ],
    [ "VertexBuffer", "class_vertex_buffer.html", "class_vertex_buffer" ],
    [ "World", "class_world.html", "class_world" ],
    [ "WorldGenerator", "class_world_generator.html", "class_world_generator" ]
];