name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: linux-build

      - name: Install prerequisites
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive

      - name: Build
        run: ./build.sh
