name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  ninja:
    name: Ninja setup
    runs-on: windows-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: win-ninja

      - name: Install cmake
        if: steps.cache-dep.outputs.cache-hit != 'true'
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Set MSVC environment
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
          arch: x64

      - name: Install Ninja
        if: steps.cache-dep.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          git submodule update --init .\lib\ninja
          cd lib\ninja
          git pull
          set /a jobs=%NUMBER_OF_PROCESSORS%+1
          cmake -S . -B .\build
          cmake --build build --config Release --clean-first --parallel %jobs%

  build-x86:
    name: Windows (x86)
    needs: ninja
    runs-on: windows-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: win-build-x86

      - name: Install cmake
        if: steps.cache-dep.outputs.cache-hit != 'true'
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive

      - name: Set MSVC environment
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
          arch: x86
          
      - name: Build
        shell: cmd
        run: |
          cd scripts
          call "win_x86.bat"
          cd ..
          set "ninja_path=%cd%\lib\ninja\build\Release\ninja.exe"
          set /a jobs=%NUMBER_OF_PROCESSORS%+1
          cmake -G Ninja -DCMAKE_MAKE_PROGRAM="%ninja_path%" -DCMAKE_BUILD_TYPE=Release -DMSVC=true -S . -B build
          cmake --build build --config Release --parallel %jobs%

  build-x64:
    name: Windows (x64)
    needs: ninja
    runs-on: windows-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: win-build-x64

      - name: Install cmake
        if: steps.cache-dep.outputs.cache-hit != 'true'
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive

      - name: Set MSVC environment
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
          arch: x64
          
      - name: Build
        shell: cmd
        run: build.bat