name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Windows build
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: win-setup-${{ matrix.platform }}

      - name: Install cmake
        if: steps.cache-dep.outputs.cache-hit != 'true'
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Build
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform }}
        run: build.bat

      - name: Acceptance test
        shell: cmd
        run: |
          start /B BlockForge.exe
          timeout /T 5
          tasklist /FI "IMAGENAME eq BlockForge.exe" 2>NUL | find /I /N "BlockForge.exe" >NUL
          if "%ERRORLEVEL%"=="0" (
            echo "Program is still running, success!"
            exit 0
          ) else (
            echo "Program fails to start!"
            exit 1
          )
