name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Windows build
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: win-setup-${{ matrix.platform }}

