name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v3
        with:
          path: lib
          key: macos-build

      - name: Install prerequisites
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: |
          brew update
          brew install cmake ninja libx11 libxrandr libxinerama libxcursor libxi mesa

      - name: Install dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive

      - name: Build
        run: ./build.sh
