name: Automated Unit Tests

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build tests
      run: msbuild test\test.csproj -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Running tests
      run: .\test\test.exe