name: Automated Unit Tests

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build tests
      run: msbuild test\test.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Running tests
      working-directory: "./test"
      run: test.exe