name: Automated Unit Tests

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]
  
jobs:
  build:
    name: Build project
    runs-on: windows-latest

    steps:
    - name: Install msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.12

    - name: Install submodules
      uses: actions/checkout@v3
      with:
       submodules: recursive

    - name: Setup libraries
      working-directory: .github
      run: setup_for_workflow.bat
      shell: cmd

    - name: Build project
      run: msbuild "Block Forge.sln" -t:rebuild -property:Configuration=Release

    - name: Share the executable to the next job
      uses: actions/upload-artifact@v3.1.0
      with:
        name: unit-tests
        path: test/test.exe

  run:
    name: Run unit tests
    runs-on: windows-latest
    needs: build

    steps:
    - name: Downloading the build executable
      uses: actions/download-artifact@v3.0.0
      with:
        name: unit-tests
        path: test

    - name: Running tests
      working-directory: test
      run: test.exe
      shell: cmd